version:  "3.3"
services:
    mongo:
      image: mongo
      restart: 'unless-stopped'
      ports:
        - 27017:27017
      expose:
        - 27017
      volumes:
        - mon-db:/data/db
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USR:-campus360}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PWD-SuperSecurePassword!}
        - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-waikato_db}

    nodejs:
      build: ./
      restart: 'unless-stopped'
      volumes:
        - images:/usr/src/app/images
      ports:
        - 3001:3001
      expose:
        - 3001
      depends_on:
        - mongo

    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_DB_NAME:-waikato_db}
            - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_RESTRICTED_USR:-remote}
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_RESTRICTED_PWD-SuperSecurePassword!}
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USR:-campus360}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PWD-campus360}
        depends_on:
            - mongo
        ports:
          - 3002:8081 
        expose:
          - 3002   
volumes:
  mon-db:
  images:
  client:
