version:  "3.3"
services:
    mongo:
      image: mongo
      restart: 'unless-stopped'
      ports:
        - 27017:27017
      expose:
        - 27017
      volumes:
        - mon-db:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=campus360
        - MONGO_INITDB_ROOT_PASSWORD=SuperSecurePassword!
        - MONGO_INITDB_DATABASE=waikato_db
    nodejs:
      build: ./NODE
      restart: 'unless-stopped'
      volumes:
        - images:/usr/src/app/images
        - client:/usr/src/app/client
      ports:
        - 3000:3000
      expose:
        - 3000
      depends_on:
        - mongo
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=waikato_db
            - ME_CONFIG_MONGODB_AUTH_USERNAME=remote
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=SuperSecurePassword!
            - ME_CONFIG_BASICAUTH_USERNAME=campus360
            - ME_CONFIG_BASICAUTH_PASSWORD=campus360
        depends_on:
            - mongo
        ports:
          - 3002:8081 
        expose:
          - 3002   
volumes:
  mon-db:
  images:
  client:
