version:  "3.3"
services:
    mongo:
      image: mongo
      restart: 'unless-stopped'
      ports:
        - 27017:27017
      expose:
        - 27017
      volumes:
        - ./MONGO:/docker-entrypoint-initdb.d
        - mon-db:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=campus360
        - MONGO_INITDB_ROOT_PASSWORD=SuperSecurePassword!
        - MONGO_INITDB_DATABASE=waikato_db
    nodejs:
      build: ./NODE
      restart: 'unless-stopped'
      ports:
        - 3000:3000
      expose:
        - 3000
      depends_on:
        - mongo
      stdin_open: true
      tty: true
volumes:
  mon-db:
